---
---

<link rel="stylesheet" href="styles.css" type="text/css">
<link rel="stylesheet" href="site_libs/academicons-1.8.6/css/academicons.css" type="text/css">

##### Journal Articles

<p style="margin-left:50px; margin-right:50px;">
**Brian T. Hamel**, and Antoine Yoshinaka. Forthcoming. ["Who Donates to Party Switchers?"](https://journals.sagepub.com/doi/full/10.1177/1532673X19858336) *American Politics Research*.
</p>

<p style="margin-left:50px; margin-right:50px;">
Atkeson, Lonna Rae, and **Brian T. Hamel**. Forthcoming. ["Fit for the Job: Candidate Qualifications and Vote Choice in Low Information Elections."](https://link.springer.com/article/10.1007/s11109-018-9486-0) *Political Behavior*.
</p>

<p style="margin-left:50px; margin-right:50px;">
**Hamel, Brian T.**, and Michael G. Miller. 2019. ["How Voters Punish and Donors Protect Legislators Embroiled in Scandal."](https://journals.sagepub.com/doi/full/10.1177/1065912918781044) *Political Research Quarterly* 72 (1): 117-131.
</p>

<p style="margin-left:50px; margin-right:50px;">
Henderson, John A., **Brian T. Hamel**, and Aaron M. Goldzimer. 2018. ["Gerrymandering Incumbency: Does Nonpartisan Redistricting Increase Electoral Competition?"](https://www.journals.uchicago.edu/doi/abs/10.1086/697120) *Journal of Politics* 80 (3): 1011-1016.
</p>

<p style="margin-left:50px; margin-right:50px;">
Panagopoulos, Costas, Jan E. Leighley, and **Brian T. Hamel**. 2017. ["Are Voters Mobilized by a `Friend-and-Neighbor' on the Ballot? Evidence from a Field Experiment."](https://link.springer.com/article/10.1007/s11109-016-9383-3) *Political Behavior* 39 (4): 865-885.
</p>

##### Under Review

<p style="margin-left:50px; margin-right:50px;">
["Corruption, Party Leaders, and Candidate Selection: Evidence from Italy"](files/working/italy_main.pdf) (with Raffaele Asquer and Miriam A. Golden). Revised & Resubmitted at *Legislative Studies Quarterly*. [Appendix](files/woking/italy_appendix.pdf).
</p>

<p style="margin-left:50px; margin-right:50px;">
["Who Gets a Streetlight? Race, Class, and Responsiveness in U.S. Cities"](files/working/311_main.pdf) (with Derek E. Holliday). [Appendix](files/working/311_appendix.pdf).
</p>

##### Selected Projects in Progress

<p style="margin-left:50px; margin-right:50px;">
"Mass Communication and Early Voting Turnout" (with Jan E. Leighley, Robert M. Stein, and Lynn Vavreck)
</p>

<p style="margin-left:50px; margin-right:50px;">
"Partisans, Nonpartisans, and Political Advertising" (with Lynn Vavreck)
</p>

<p style="margin-left:50px; margin-right:50px;">
"Measuring Racial Context" (with Bryan Wilcox-Archuleta)
</p>

<p style="margin-left:50px; margin-right:50px;">
"Poverty, Inequality, and Political Preferences" (with Eunji Kim)
</p>

<p style="margin-left:50px; margin-right:50px;">
"The Political Legacy of Head Start" (with John B. Holbein, Soumyajit Mazumder, and Alan N. Yan)
</p>

<p style="margin-left:50px; margin-right:50px;">
"The Causal Effects of Unions" (with Soumyajit Mazumder)
</p>

<p style="margin-left:50px; margin-right:50px;">
"Campaign Finance Limits in the U.S. States" (with Aaron M. Goldzimer, John A. Henderson, and Shawn Patterson, Jr.)
</p>


